benchmarks:
- judgebench
evaluation_config:
  dataset_mode: full
  lm: openrouter/meta-llama/llama-3.3-70b-instruct
  lm_api_base: https://openrouter.ai/api/v1
  num_threads: 416
  max_concurrent_processes: 8
optimization:
  base_url: https://openrouter.ai/api/v1
  max_concurrent: 48
  model: meta-llama/llama-3.3-70b-instruct
  sample_size: 25
  strategies:
  - openai_v2_research_paper_generated_with_few_data
  - metaai_research_paper_generated_with_few_data
  - self_written_2
  - self_written
  - llama_405b
  temperature: 0.3
output_dir: meta-optimize-prompt
